#
# Lista de exericios 04
# Busca de motivos em sequencias
#
# Pedro Cantarutti

seq =
{
    'NC_002119.1:c3231-3032 Escherichia coli K-12 P678-54 plasmid CloDF13':
    'ATCTCATATATTGACACCTGAAAACTGGAGGAGTAAGGTAATAATCATACTGTGTATATATACAGTATTT
    TGGTTTTAATTTATTGTTTTAAATGTCAAAGAGGAAAACGATATGAGTGGTGGAGACGGTCGAGGTCCGG
    GTAATTCAGGTCTGGGACATAATGGTGGTCAGGCCAGTGGGAATGTGAACGGTACGTCTG',

    'J01563.1:26-225 Plasmid ColE1 colicin E1 gene':
    'GAATAGCGCGTGGTGTGAAAGACTGTTTTTTTGATCGTTTTCACAAAAATGGAAGTCCACAGTCTTGACA
    GGGAAAATGCAGCGGCGTAGCTTTTATGCTGTATATAAAACCAGTGGTTATATGTACAGTATTTATTTTT
    AACTTATTGTTTTAAAAGTCAAAGAGGATTTTATAATGGAAACCGCGGTAGCGTACTATA',

    'M13819.2:830-1029 Plasmid ColIa':
    'GACATGCCATTTTCTCCTTAATAAATTAATACTGTATATGTATCCATATGCGTAAGCAGTTAATTCATTT
    GTTTTCCTCAGAGGATGAAGGAGATACCGAATGTCTGACCCTGTACGTATTACAAATCCCGGTGCAGAAT
    CGCTGGGGTATGATTCAGATGGCCATGAAATTATGGCCGTTGATATTTATGTAAACCCTC',

    'X01009.1:752-951 E. coli plasmid ColIb DNA':
    'ATGCTGCCACAGTGTCAGCAGGCTTTCTGAACGGTATAACACCACTTCATGTTAATGATAATTACTATCA
    TTAAATCTTGACATGCCATTTTCTCCTTAATAAATTAGTACTGTATATGTATCCATATACGTAAGCAGTT
    AATTCATTTGTTTTCCTCAGAGGATGAAGGAGATACCGAATGTCTGACCCTGTACGTATT',

    'V00328.1:91-290 E. coli recA gene':
    'GCGGTGCGTCGTCAGGCTACTGCGTATGCATTGCAGACCTTGTGGCAACAATTTCTACAAAACACTTGAT
    ACTGTATGAGCATACAGTATAATTGCTTCAACAGAACATATTGACTATCCGGTATTACCCGGCATGACAG
    GAGTAAAAATGGCTATCGACGAAAACAAACAGAAAGCGTTGGCGGCAGCACTGGGCCAGA',

    'Y00357.1:291-490 E. coli recN gene':
    'AAAAAAATTATTCTAATTTTACGCCAGCCTCTTTACTGTATATAAAACCAGTTTATACTGTACACAATAA
    CAGTAATGGTTTTTCATACAGGAAACGACTATGTTGGCACAACTGACCATCAGCAACTTTGCTATCGTTC
    GTGAGCTTGAGATTGATTTTCATAGCGGCATGACCGTAATAACTGGCGAGACCGGCGCGG',

    'NC_000913.3:c1021019-1020820 Escherichia coli str. K-12 substr. MG1655':
    'CGACAAAATTTGCGAGGCTCTTTCCGAAAATAGGGTTGATCTTTGTTGTCACTGGATGTACTGTACATCC
    ATACAGTAACTCACAGGGGCTGGATTGATTATGTACACTTCAGGCTATGCACATCGTTCTTCGTCGTTCT
    CATCCGCAGCAAGTAAAATTGCGCGTGTCTCTACGGAAAACACTACAGCCGGGCTTATCA',

    'M10107.1:321-520 E.coli umu operon: umuD and umuC':
    'GCACAAGATAAGAGAACGAAAAATCAGCAGCCTATGCAGCGACAAATATTGATAGCCTGAATCAGTATTG
    ATCTGCTGGCAAGAACAGACTACTGTATATAAAAACAGTATAACTTCAGGCAGATTATTATGTTGTTTAT
    CAAGCCTGCGGATCTCCGCGAAATTGTGACTTTTCCGCTATTTAGCGATCTTGTTCAGTG',

    'J01721.1:95-294 Escherichia coli single-stranded DNA-binding protein':
    'TTCCGCGAAACAAACCTGGCCAGACATTGTTACACAACACTCCGGGTAATGCATTCCAATACTGTATATT
    CATTCAGGTCAATTTGTGTCATAATTAACCGTTTGTGATCGCCGGTAGCACCATGCCACCGGGCAAAAAA
    GCGTTTAATCCGGGAAAGGTGAATGGATAAGATCGAAGTTCGGGGCGCCCGCACCCATAA',

    'X03678.1:346-545 E. coli gene for uvrB protein of ABC excinuclease':
    'GTGATGAACTGTTTTTTTATCCAGTATAATTTGTTGGGATAATTAAGTACGACGAGTAAAATTACATACC
    TGCCCGCCCAACTCCTTCAGGTAGCGACTCATGAGTAAACCGTTCAAACTGAATTCCGCTTTTAAACCTT
    CTGGCGATCAGCCAGAGGCGATTCGACGTCTCGAAGAGGGGCTGGAAGATGGCCTGGCGC',

    'D00069.1:254-453 Escherichia coli uvrD gene':
    'CCGGAAAATGGCGATCTGATGCAAACCTGGGACAGCCGTTTACTGCCGCATCTGGAAATTTCCCGGTTGG
    CATCTCTGACCTCGCTGATATAATCAGCAAATCTGTATATATACCCAGCTTTTTGGCGGAGGGCGTTGCG
    CTTCTCCGCCCAACCTATTTTTACGCGGCGGTGCCAATGGACGTTTCTTACCTGCTCGAC'
}



if __name__=='__main__':
    print('Ya')
